---
- name: this Ansible Playbook will terminate un-tagged instances
  hosts: localhost
  gather_facts: false
  vars:
    ec2_region: "{{ your_region | default('eu-central-1') }}"
  tasks:
    - name: grab info for un-tagged instances
      community.aws.ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          instance-state-name: running
      register: ec2_node_info

    - name: set the untagged to a var
      set_fact:
        untagged_instances: "{{ ec2_node_info.instances | selectattr('tags', 'equalto', {}) | map(attribute='instance_id') | list }}"

    - name: print out how many instances were found
      debug:
        msg: "There are {{ untagged_instances | length }} un-tagged hosts on region {{ ec2_region }}"
      run_once: true

    - name: Terminate every un-tagged running instance in a region.
      community.aws.ec2:
        region: "{{ ec2_region }}"
        state: absent
        instance_ids: "{{ untagged_instances }}"
      when: untagged_instances | length  > 0
